version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.10.3

    working_directory: /go/src/github.com/lab259/errors
    steps:
      - checkout

      - run:
          name: Installing Ginkgo
          command: go get -u github.com/onsi/ginkgo/ginkgo

      - run:
          name: Installing dependencies
          command: make dep-ensure

      - run:
          name: Run tests
          command: |
            make coverage-ci

      - run: bash <(curl -s https://codecov.io/bash)
